Lms_key/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from Lms import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('books/', include('books.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views
app_name='books'

urlpatterns = [

    path('',views.all_bookss,name='all_bookss'),
    path('<int:books_id>',views.detail,name='detail'),

]

Lms/models.py
from django.db import models

class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to='Lms/images/')
    url=models.URLField(blank=True)
    def __str__(self):
        return self.title

books/models.py
from django.db import models

# Create your models here.
class Books(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    date=models.DateField()
    def __str__(self):
        return self.title

Lms/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects=Project.objects.all()
    return render(request, 'Lms/home.html',{'projects':projects})

books/views.py
from django.shortcuts import render, get_object_or_404
from .models import Books

def all_bookss(request):
    bookss=Books.objects.order_by('-date')
    return render(request,'books/all_bookss.html',{'bookss':bookss})
# Create your views here.
def detail(request,books_id):
    books= get_object_or_404(Books,pk=books_id)
    return render(request,'books/detail.html',{'books':books})

Lms/templates/Lms/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "Lms/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "Lms/Logo.jpg" %}">

  <title>Keywordio LMS</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "Lms/Logo.jpg" %}" width="30" height="30" class="d-inline-block align-top">
        <span>LM System</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/kumar-reddy-gude-82809222a" target="_blank">LinkedIn</a>
          </li>

          <li>
            <a role="button" href="{% url 'books:all_bookss' %}" class="btn btn-primary">Library</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

Lms/templates/Lms/home.html
{% extends "Lms/base.html" %}

{% load static %}

{% block content %}



<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Hey! Welcome to Keywordio Library</h1>
  </div>
</div>

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'Lms/Rio.png' %}" class="img-fluid">
  </div>
</div>

<h2>To check the books click on <b> Library </b>button available on the top tight corner.</h2>



<h2 class="mt-5"><b>Sample Books</b></h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}

books/templates/books/all_bookss.html
{% extends "Lms/base.html" %}

{% load static %}

{% block content %}

<h2 id="bookstitle" class="font-weight-bold text-center">Keywordio LMS</h2>

<h3 class="text-center mb-5">Books available :{{ bookss.count }} Book{{ bookss.count|pluralize }}</h3>

{% for books in bookss %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'books:detail' books.id %}">
      <h2>{{ books.title }}</h2>
    </a>
    <h5 class="text-muted">{{ books.date|date:'M d Y'|upper }}</h5>
    <h4>{{ books.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

books/templates/books/detail.html
{% extends "Lms/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="booksdetailtitle">{{ books.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ books.date|date:'F jS Y' }}</h5>

{{ books.description|safe }}

{% endblock %}